services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/static/static/
      - media:/app/media

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - static:/static/static/
      - frontend_build:/app/build

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway
    build: ./nginx/
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - static:/static/static/
      - media:/app/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build: 