version: '3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ekaterinakaiser/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: ekaterinakaiser/kittygram_frontend
    env_file: .env
    volumes:
      - ../frontend/build:/app/result_build/
    command: cp -r /app/build/. /app/result_build/

  gateway:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - static:/static/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static:
  media: 