version: '3'

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static_backend:/static/
      - media:/app/media

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend
    volumes:
      - static_frontend:/usr/share/nginx/html/

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway
    ports:
      - 80:80
    volumes:
      - static_frontend:/usr/share/nginx/html/
      - static_backend:/static/backend/
      - media:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_backend:
  static_frontend:
  media: 