version: '3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kittygram_network

  backend:
    image: ekaterinakaiser/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
    networks:
      - kittygram_network

  frontend:
    image: ekaterinakaiserkittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
    networks:
      - kittygram_network

  gateway:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network

volumes:
  postgres_data:
  static:
  media:

networks:
  kittygram_network:
    driver: bridge 