services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: kittygram_user
      POSTGRES_PASSWORD: kittygram_password
      POSTGRES_DB: kittygram
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend

networks:
  kittygram_network:
    driver: bridge 

volumes:
  pg_data:
  static:
  media:
  frontend_build: 