ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
    - "${SSH_KEY}"
write_files:
  - path: "/root/vm_prep.sh"
    permissions: "0740"
    content: |
      #!/bin/bash

      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl start docker
      sudo systemctl enable docker
      sudo usermod -aG docker $USER
      newgrp docker
      
      sudo apt-get install -y docker-compose-plugin
      docker compose version
      
runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh